lunar-gateway:
  version: v1
  server:
    security:
      cert: path/to/file/
      key: path/to/file/
      trusted: path/to/file/
    address: localhost:8080
    dialtimeout: 5
    requesttimeout: 10
  services:
    celestial: localhost:8000
    blackhole: localhost:8082
    apollo: localhost:8083
    stellar: localhost:8007
  instrument:
    address: 0.0.0.0:4222
    stopic: collector
    collect: 15s
    location: logs/
