gateway:
  route: /apis
  port: 5555
services:
  Magnetar: magnetar:5000
  Kuiper: kuiper:9001
  AuthService: iam-service:8002
  OortAdministrator: oort:8000
groups:
  core:
    v1:
      RegisterUser:
        method_route: /user/register
        type: POST
        service: AuthService
      LoginUser:
        method_route: /user/login
        type: POST
        service: AuthService
      ListNodePool:
        method_route: /nodes/list
        type: GET
        service: Magnetar
      ClaimOwnership:
        method_route: /nodes/ownership
        type: POST
        service: Magnetar
      PutFloat64Label:
        method_route: /nodes/put_label
        type: POST
        service: Magnetar
      QueryOrgOwnedNodes:
        method_route: /org/nodes
        type: POST
        service: Magnetar
      CreateInheritanceRel:
        method_route: /relations
        type: POST
        service: OortAdministrator
      CreatePolicy:
        method_route: /policies
        type: POST
        service: OortAdministrator
      PutConfigGroup:
        method_route: /config_groups
        type: POST
        service: Kuiper
      ApplyConfigGroup:
        method_route: /apply_config
        type: POST
        service: Kuiper
