gateway:
  route: /apis
  port: 5555
services:
  Magnetar: magnetar:5000
  Kuiper: kuiper:9001
  AuthService: iam-service:8002
  OortAdministrator: oort:8000
groups:
  core:
    v1:
      RegisterUser:
        method_route: /user
        type: POST
        service: AuthService
      LoginUser:
        method_route: /auth
        type: POST
        service: AuthService
      ListNodePool:
        method_route: /nodes/available
        type: GET
        service: Magnetar
      ListOrgOwnedNodes:
        method_route: /nodes/allocated
        type: GET
        service: Magnetar
      QueryNodePool:
        method_route: /nodes/available/query_match
        type: GET
        service: Magnetar
      QueryOrgOwnedNodes:
        method_route: /nodes/allocated/query_match
        type: GET
        service: Magnetar
      ClaimOwnership:
        method_route: /nodes
        type: PATCH
        service: Magnetar
      PutFloat64Label:
        method_route: /labels/float64
        type: POST
        service: Magnetar
      PutBoolLabel:
        method_route: /labels/bool
        type: POST
        service: Magnetar
      PutStringLabel:
        method_route: /labels/string
        type: POST
        service: Magnetar
      DeleteLabel:
        method_route: /labels
        type: DELETE
        service: Magnetar
      CreateInheritanceRel:
        method_route: /relations
        type: POST
        service: OortAdministrator
      CreatePolicy:
        method_route: /policies
        type: POST
        service: OortAdministrator
      PutConfigGroup:
        method_route: /configs
        type: POST
        service: Kuiper
      ApplyConfigGroup:
        method_route: /configs/applications
        type: POST
        service: Kuiper
